### ISSUE TITLE
Check compatibility with VSCode 1.23

### ISSUE THREAD

**Issue by gilmoreorless** [gilmoreorless/vscode-zoneinfo#2]
VSCode v1.23 introduced new FileSystem providers: https://code.visualstudio.com/updates/v1_23#_filesystem-providers

> The addition of FileSystem Providers means that not all files live on disk and extensions should be aware of this. The short, but **important**, message is that not all documents live on disk and if your extension relies on disk-access, you **must** check the scheme first.

I should double-check that this extension handles files correctly.

**Comment by jasonwilliams** [comment]
I think this issue can be closed. We’re on 1.50 now and the extension works fine. I believe the file provider change was backwards compatible.

**Comment by gilmoreorless** [comment]
👍 Good point. Clearly I let some of these issues (a.k.a. glorified TODO notes-to-self) linger a bit longer than I first intended. 😉
